# Generated by Django 4.2.1 on 2023-07-05 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dept",
            fields=[
                ("deptno", models.IntegerField(primary_key=True, serialize=False)),
                ("deptname", models.CharField(max_length=100)),
                ("deptloc", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Emp",
            fields=[
                ("empno", models.IntegerField(primary_key=True, serialize=False)),
                ("empname", models.CharField(max_length=100)),
                (
                    "deptno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.dept"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(model_name="price", name="memberships",),
        migrations.DeleteModel(name="Member",),
        migrations.DeleteModel(name="Price",),
    ]
